Numpy 연습문제

In [1]:
import numpy as np

1 행렬만들기

In [2]:
np.arange(10, 81, 10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2 Indexing, Slicing

In [4]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])

In [5]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
m[1,2], m[-1,-1], m[1,1:3], m[1:,2], m[:-1,-2:]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

3 Boolean indexing

In [7]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
m.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
m[(m % 3 == 0) & (m > 0)]

array([ 3,  6,  9, 12])

In [10]:
m[m % 4 == 1]

array([ 1,  5,  9, 13])

In [11]:
m[(m % 3 == 0) & (m % 4 == 1)]

array([9])

In [12]:
# 위 두개의 교집합
f[np.logical_and(f % 3 == 0, f % 4 == 1)]

array([9])

4 대각선 행렬

In [13]:
np.eye(N=5, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.eye(5,5,-1,int)*3 + np.eye(5,5,0,int)*2 + np.eye(5,5,1,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

5 Matrix operation

In [15]:
np.random.seed(2021)
mm = np.random.uniform(0, 10, 30).reshape(5, 6).round(4)
mm

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [16]:
# 전체의 최댓값
mm.max()

9.9724

In [17]:
# 행의 합
mm.sum(axis=1)
# np.sum(a, axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [18]:
# 행의 최댓값
mm.max(axis=1)
# np.max(a, axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [19]:
# 열의 평균값
mm.mean(axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [20]:
# 열의 최솟값
mm.min(axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

6 Sorting

In [21]:
nn = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
nn

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [22]:
# 영어성적 정렬
np.sort(nn[1])[::-1]

array([100,  99,  71,  46])

In [23]:
# 영어성적 내림차순의 Index값
indices = np.argsort(nn[1])[::-1]
indices

array([2, 1, 3, 0], dtype=int64)

In [24]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
nn[:, indices]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [25]:
# 한 줄로 표현
nn[:, np.argsort(nn[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

7 주사위 100번

In [26]:
np.random.seed(2021)
dice = np.random.randint(1, 7, 100)
dice.mean()

3.7

In [27]:
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [28]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

In [29]:
import pandas as pd
s = pd.Series(counts, index=unique)
s

1     8
2    21
3    19
4    18
5    13
6    21
dtype: int64

8 정규 분포

In [30]:
# 5개만 먼저 테스트
np.random.seed(2021)
rate = np.random.randn(5) * 0.01
rate

array([ 0.01488609,  0.00676011, -0.00418451, -0.00806521,  0.00555876])

In [31]:
price = 10000
for i in range(5):
    price = price * rate[i] + price
    # price += price * rate[i]
    price = np.round(price)
    print(int(price), end=' ')

10149 10218 10175 10093 10149 

In [32]:
# 250개np.random.seed(2021)
np.random.seed(2021)
rate = np.random.randn(250) * 0.01
price_list = [10000]
for i in range(250):
    price = price_list[i] * (1 + rate[i])
    price = np.round(price)
    price_list.append(int(price))

price_list[:10]


[10000, 10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257, 10268]

In [33]:
len(price_list)

251

In [34]:
# epmty를 써서
np.random.seed(2021)
rate = np.random.randn(250) * 0.01
price_array = np.empty(251, int)
price_array[0] = 10000
for i in range(250):
    price = price_array[i] * (1 + rate[i])
    price = np.round(price)
    price_array[i+1] = int(price)

price_array[:10]

array([10000, 10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257,
       10268])

추가

In [35]:
np.inf # 실수

inf